services:
    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx.Dockerfile
        depends_on:
            - php
            - mysql
            - phpmyadmin
        container_name: laravel_nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./src:/var/www/html

    php:
        build:
            context: .
            dockerfile: ./docker/php.Dockerfile
        container_name: laravel_php
        volumes:
            - ./src:/var/www/html

    mysql:
        image: mysql:8.0.27
        platform: linux/amd64
        container_name: laravel_mysql
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: reinz
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: laravel_phpmyadmin
        ports:
            - 8080:80
        environment:
            PMA_HOST: laravel_mysql
            PMA_USER: user
            PMA_PASSWORD: password
        depends_on:
            - mysql

    composer:
        image: composer:latest
        container_name: laravel_composer
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html

    artisan:
        build:
            context: .
            dockerfile: ./docker/php.Dockerfile
        container_name: laravel_artisan
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        entrypoint: ['php', 'artisan']

    npm:
        image: node:current-alpine
        container_name: laravel_npm
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        entrypoint: ['npm']